### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by simonnelli** [johannrichard/homebridge-dingz#1]
Thank you so much for this implementation.  I was able to add Dingz to Homebridge (via Config UI) but it seems like the dip-Switches are not recognized correctly. The dip switches are both set to 'light' but Dingz is shown as a 'Window Covering' device in HomeKit.

Furthermore this is what is shown in the log:
`[5/14/2020, 3:54:29 PM] [Dingz] Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /homebridge/node_modules/homebridge-dingz/node_modules/servie/src/node.ts:104:39
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at DingzDaHomebridgePlatform.fetch (/homebridge/node_modules/homebridge-dingz/src/platform.ts:500:25)
    at DingzDaAccessory.getWindowCovering (/homebridge/node_modules/homebridge-dingz/src/dingzDaAccessory.ts:1005:19)`

HomeBridge (using it for hue and Sonos) is running inside a docking container on a Synology NAS.

<img width="611" alt="Screenshot 2020-05-14 at 15 54 08" src="https://user-images.githubusercontent.com/32964940/81943206-60b49a00-95fb-11ea-9c84-be32b2328be3.png"><img width="467" alt="Screenshot 2020-05-14 at 15 50 20" src="https://user-images.githubusercontent.com/32964940/81943216-6316f400-95fb-11ea-9cd8-0d3404f73a60.png">

**Comment by johannrichard** [comment]
Thanks for the feedback. Could you post the output / value of the `dip_config` you get when you access `http://192.168.227.54/api/v1/device/`?  (Feel free to remove the MAC address of your device)

For some features I had to exclusively rely on the API documentation -- could well be some things are amiss here.

**Comment by simonnelli** [comment]
There you go!

`{"type":"dingz","battery":false,"reachable":true,"meshroot":true,"fw_version":"1.1.49","hw_version":"1.0","fw_version_puck":"1.1.18","bl_version_puck":"1.0.0","hw_version_puck":"1.1.1","hw_id_puck":1,"puck_sn":"","puck_production_date":{"year":19,"month":12,"day":14},"puck_hw_model":"","dip_config":3,"has_pir":true,"hash":"cfb63dd7"}}`

**Comment by johannrichard** [comment]
Just pushed 8983213cabd573519b7414bb0dea4b33adc6be66 and `v1.0.1` of the plugin on NPM which inverts the detection of the DIP switches. Could you check whether the blinds are being replaced by Lights now? (You might have to remove the accessory and add it again to be sure the plugin picks up the right values)

**Comment by simonnelli** [comment]
Works perfect now, thank you! (Can only verify by looking remotely at HomeBridge UI, can check with iPhone when I'm on site tomorrow, don't have a HomeKit-Hub in place yet).

 I'd rename the Dimmers to 1-4 instead of 0-3 to be consistent with the web interface of Dingz.

Do you plan to expose the buttons to HomeKit as well? By doing this other HomeKit-Workflows and devices could be triggered by pushing the buttons on Dingz.

**Comment by johannrichard** [comment]
Thanks for the feedback and the suggestion. Glad it works. 

I plan to add support for buttons at some point in time but that requires a bit more „Gehirnschmalz“ on how to deal with getting the button pushes. It essentially requires a REST API for the plugin.
