### ISSUE TITLE
[BUG] No connection, "TypeError: Cannot read property 'blind' of undefined"

### ISSUE THREAD

**Issue by mabu4ch** [johannrichard/homebridge-dingz#11]
The plugin does not work for me. Although devices appear in "Home" they cannot be controlled. Also other plugins are not working anymore.

**To Reproduce**
I have one dingz connected to my network. It is setup to use Output 2 as button and output 3/4 to control a blind. I just install the plugin and observe. See copy from log file below

**Plugin environment (please complete the following information):**
 - Homebridge Server: Homebridge on RaspberryPI
 - Plugin Version : homebridge-dingz v1.5.0
 - Node.js Version: v12.14.1
 - Homebridge Version:  1.1.0
 - Special settings: with auto-discovery

**Screenshots**
The log file might give a hint for the reason for this behaviour:

[Dingz & myStrom SmartHome platform] Update accessory -> Check for changed config.
(node:22232) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'blind' of undefined
    at DingzDaAccessory.updateWindowCoveringState (/usr/local/lib/node_modules/homebridge-dingz/src/dingzAccessory.ts:817:33)
    at DingzEventBus.emit (events.js:228:7)
    at /usr/local/lib/node_modules/homebridge-dingz/src/dingzAccessory.ts:200:32
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:22232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)

**Additional context**

**Comment by johannrichard** [comment]
Thanks! Blinds are a topic I can't fully test on my own. There are some users using dingz with blind successfully yet others had trouble in the past though, so let's try to find out what's amiss here. 

May I ask you to provide the following additional info for me to better debug (Feel free to change/obfuscate the MAC addresses and IP addresses in the output): 

* The output from `http://<yourdingz-ip>/api/v1/device`
* The output from `http://<yourdingz-ip>/api/v1/state`

Thank you.

**Comment by mabu4ch** [comment]
Thanks for looking into this:
.../device:
{"246F28A69C2C":{"type":"dingz","battery":false,"reachable":true,"meshroot":true,"fw_version":"1.1.49","hw_version":"1.1.2","fw_version_puck":"1.1.18","bl_version_puck":"1.0.0","hw_version_puck":"1.1.2","hw_id_puck":65535,"puck_sn":"B20042500159","puck_production_date":{"year":20,"month":4,"day":25},"puck_hw_model":"DZ1B-4CH","front_hw_model":"dz1f-pir","front_production_date":"20/4/24","front_sn":"F20042400032","dip_config":1,"has_pir":true,"hash":"cfb63dd7"}}

.../state:
{"dimmers":[{"on":false,"output":0,"ramp":0,"readonly":false,"index":{"relative":0,"absolute":0}},{"on":false,"output":0,"ramp":0,"readonly":false,"index":{"relative":1,"absolute":1}}],"blinds":[{"moving":"stop","position":100,"lamella":100,"readonly":false,"index":{"relative":0,"absolute":1}}],"led":{"on":false,"hsv":"302;100;49","rgb":"FFFFFF","mode":"hsv","ramp":100},"sensors":{"brightness":1,"light_state":"night","room_temperature":20.71,"uncompensated_temperature":32.3125,"cpu_temperature":68.27,"puck_temperature":32,"fet_temperature":38,"person_present":0,"input_state":null,"power_outputs":[{"value":0},{"value":0},{"value":0},{"value":0}]},"thermostat":{"active":false,"out":0,"on":false,"enabled":true,"target_temp":21,"mode":"heating","temp":20.200000762939453,"min_target_temp":17,"max_target_temp":31},"config":{"timestamp":1590603818}}

One thing you might want to look at is that I have the blind connected to outputs 3/4 resulting in dip_config=1

I took the freedom to look at the code. Shouldn't the line 457 maybe take 1 as WindowCoveringId?
instead of        windowCoverServices.push(this.addWindowCoveringService('Blind', 0));
        windowCoverServices.push(this.addWindowCoveringService('Blind', 1)); 
probably not...

**Comment by johannrichard** [comment]
Thanks, your inputs were helpful: The state of the blinds is returned different in the `state` endpoint compared to the the dedicated endpoint. I've published a test version (`1.5.1-nightly.0`) where this should be fixed (no guarantee as I can't test myself) which you can install with `npm i homebridge-dingz@testing` from the terminal of the homebridge server. 

If you have Homebridge Config UI X under Docker running, the easiest way to access this is via `Settings` -> `Terminal`. In that case the plugin will simply be overwritten if you restart the entire Docker Container but will remain installed if you only restart homebridge itself. 

I'd appreciate if you can give me feedback whether this fixes it or not. Thanks for your help!

**Comment by mabu4ch** [comment]
Thanks for the update. It is a big improvement. Homebridge keeps running and dingz is listed in "Home". 
The state  of the blind is not updated (open, closed) and also controlling the blind does not work.
Here's what I see in the log (ip address is "obfuscated"):
[6/1/2020, 08:54:31] [Dingz & myStrom SmartHome platform] HTTP Response Error ->http://192.168.xxx.xxx/api/v1/shade/0/
[6/1/2020, 08:54:31] [Dingz & myStrom SmartHome platform] Request failed with status code 400
[6/1/2020, 08:54:31] [Dingz & myStrom SmartHome platform] 
[6/1/2020, 08:54:31] [Dingz & myStrom SmartHome platform] 400
[6/1/2020, 08:54:31] [Dingz & myStrom SmartHome platform] {
  connection: 'close',
  'content-type': 'text/html',
  'content-length': '0',
  'access-control-allow-origin': '*'
}

**Comment by johannrichard** [comment]
OK. This seems to be another point when *setting* the blinds. 

If you open `http://192.168.xxx.xxx/api/v1/shade/0/` *and* `http://192.168.xxx.xxx/api/v1/shade/1/` in your browser,  can you post here what you receive in return (I would guess noting for `/0/` and some JSON w/ `target` and `current` for blind and lamella in the case of `/0/`)?

**Comment by mabu4ch** [comment]
I only get an answer for shade/0/ (see below)
shade/1/ gives http error 404

// 20200601164027
// http://192.168.xxx.xxx/api/v1/shade/0/

{
  "target": {
    "blind": 100,
    "lamella": 100
  },
  "current": {
    "blind": 100,
    "lamella": 100,
    "disabled": false,
    "index": {
      "relative": 0,
      "absolute": 1
    }
  }
}

also the state of the blinds is not reflected correctly

**Comment by johannrichard** [comment]
Thanks! I've reworked some more code for edge cases related to the state endpoint I'm using, so there's a new nightly `1.5.1-nightly.1` that you could try out if you find some time. I'm not exactly sure about the state being reflected correctly right now, but the error you reported should be gone. 

> BTW It seems that the api is a bit inconsistent:
while
http://192.168.xxx.xxx/api/v1/state has a "position" property in the blinds array
http://192.168.xxx.xxx/api/v1/shade/0/ seems to use a "blind" property for the same thing

Yup, there are some inconsistencies in the API I have to work around, and this is one: For the dimmers, the returned data was exactly the same for `/api/v1/dimmer/` and for `/api/v1/state` -- for blinds, it very apparently isn't. 

As you know, I'm doing this in my free time -- I'm not affiliated with Iolo or myStrom in any way and do my best to improve the plugin over time. I also don't have access to a complete test-environment, i.e. all kinds of dingz with all configuration permutations, hence I'm sometimes programming "blind" - most fittingly with the blinds. So far, we've managed to squash all bugs thanks to patient users like you, so thanks for helping out with this one.

**Comment by mabu4ch** [comment]
It looks alright now! Great work.

Yes, I thought that you were spending your free time for this. 
Although the functionality was not really important at this time I thought I'd give it a try with this plugin and out of personal interest just see what happens. So I filed this bug. It's great that you were so responsive and in turn wanted to help. So if I have time and you want something to be looked at...
I think I can close the issue now, right?

**Comment by johannrichard** [comment]
Thanks for helping out too.
