### ISSUE TITLE
[BUG] No up-to-date light and temperature values in Homebridge anymore

### ISSUE THREAD

**Issue by qx54** [johannrichard/homebridge-dingz#123]
**Describe the bug**
Temperature and light don't get updated in Homebridge and Home app anymore, although `http://<PIR-IP>/api/v1/sensors` shows up-to-date temperature and light values.

**To Reproduce**
1. In the Homebridge GUI navigate to _Accessories_
2. Light will have an old value
3. Open `http://<PIR-IP>/api/v1/sensors` in browser
4. Light value will be different, but correct

**Expected behavior**
The light and temperature values in Homebridge should have the same values as the ones provided by the API.

**Plugin environment:**
- myStrom PIR Firmware Version: 3.8.2
- Homebridge Server: Raspberry Pi 4
- Plugin Version: 1.8.0
- Node.js Version: 14.15.1
- Homebridge Version: 1.1.6

**Additional context**
The issue appears only after some time. Upon re-starting Homebridge it works again, but will stop working after a couple of hours.

**Comment by johannrichard** [comment]
The change related to reachability (73298a58f2cfbf3dff2a12e146ab1d137b2aac64) introduced in `v1.8.0` seems to break quite a few things, but only after some time running. 🤦 A downgrade to `v1.7.1` should work around this while I work on a fix.

**Comment by johannrichard** [comment]
I've released `homebridge-dingz@1.8.3-nightly.0` (`homebridge-dingz@nightly`) and am running it now. If you want to help with testing, feel free to install it and report back. 

- the nightly reverts some of the changes that might have caused some of the problems encountered here and elsewhere 🤕🤒

**Comment by qx54** [comment]
I've installed 1.8.3 nightly and will report back 👍

**Comment by johannrichard** [comment]
In the meantime I've worked on a `v2.0.0-nightly` of the plug-in. If you reinstall the nightly w/ `homebridge-dingz@nightly` you should be upgraded to this version.

The functionality remains largely the same but the code is less cluttered and better structured so should generally run better. There might be bugs though but you can always downgrade to `v1.8.3-nightly` (although I think the newest nightlies are much more robust).

I've had it running over longer periods of time now on my production dingz. So far I could not observe any problems with temperature/brightness values not updating. 

(The easiest way to test if it still works after a few hours is to use your phone's flashlight to illuminate or your hand to darken the illumination: the LUX value should change significantly 😄)

**Comment by johannrichard** [comment]
It's apparently still not fixed though. 🤦 😞 But I now have a clue where it happened (unreleased mutex locks on the request queue) in the code. :octocat:

https://github.com/johannrichard/homebridge-dingz/blob/dee30b26ab348adb4db62c7f90f47c4ae107b684/src/dingzAccessory.ts#L1585-L1597

**Comment by qx54** [comment]
So far v2.0.0-nightly is working for me, but it has been running less than 24 hours.
