### ISSUE TITLE
[BUG] HTTP Response Error in Log

### ISSUE THREAD

**Issue by simonnelli** [johannrichard/homebridge-dingz#135]
**Describe the bug**
Since updating to v2.0.0-nightly I often get following error message in the log. Everything works as expected as I can see.

~~~
[11/25/2020, 8:40:32 AM] [dingz] HTTP Response Error ->http://192.168.227.12/api/v1/dimmer/2/off/
[11/25/2020, 8:40:32 AM] [dingz] Request failed with status code 404
[11/25/2020, 8:40:32 AM] [dingz] 
[11/25/2020, 8:40:32 AM] [dingz] 404
[11/25/2020, 8:40:32 AM] [dingz] {
  connection: 'close',
  'content-type': 'text/html',
  'content-length': '0',
  'access-control-allow-origin': '*'
}

~~~

**To Reproduce**
Install v2.0.0-nightly, check log

**Expected behavior**
no errors in log

**Plugin environment (please complete the following information):**
 - dingz/myStrom Device Firmware Version [e.g. 1.49.0]
 - Homebridge Server: [e.g. Homebridge Docker]
 - Plugin Version [e.g. 1.5.0]
 - Node.js Version [e.g. 14.1.0]
 - Homebridge Version [e.g. 1.1.0]
 - Special settings [e.g. with/without auto-discovery]

**Screenshots and Logs**

You can enclose log files, JSON output from API endpoints and other output in a *code fence* like this:

~~~markdown
```
Code or Log output
```
~~~

This makes it easier to read for the developer (and yourself). You can even add the language used for better formatting:

~~~
```json 
{  
    "employee": {  
        "name":       "sonoo",   
        "salary":      56000,   
        "married":    true  
    }  
}  
```
~~~

will be rendered as 

```json
{  
    "employee": {  
        "name":       "sonoo",   
        "salary":      56000,   
        "married":    true  
    }  
}  
```

**Additional context**

**Comment by johannrichard** [comment]
Will be fixed when 70e88aa7c3eca0dc2f57f6ddc6dee7e391b2b269 is merged into master (with the upcoming `v2.0.0` release. Nightlies should already have fixed it.
