### ISSUE TITLE
[TESTING] 2.0.0-rc (Release Candidate)

### ISSUE THREAD

**Issue by johannrichard** [johannrichard/homebridge-dingz#139]
I've just released a "release candidate" of the plugin. You can install it in your homebridge by running `npm i homebridge-dingz@next` from the Terminal in Homebridge Config UI X or your command line and then restart homebridge.

One note: it will **BREAK YOUR BLINDS** -- I had to implement a change that is unfortunately incompatible with old setups. It should be much more reliable now but I can't tell for sure. If you have a test-server you can run along your main server to do the testing, that will help (you can also run a local homebridge instance on your computer for some testing and to avoid touching your main setup -- you will just have to set-up a new *Home* in HomeKit and add the bridge there).
 
Please have a look at it. It should fix quite a few problems and will make it easier to solve additional little ones. I'd be grateful to see some testing before I release this as a major version. 

Release notes can be found here: [v2.0.0-rc](https://github.com/johannrichard/homebridge-dingz/releases/tag/v2.0.0-rc)

Fixes and implements changes and bugs reported in #3, #103, #116, #120, #123, #124, #129, #135 
(@qx54, @granturism0, @simonnelli: I'd be very grateful if you could help with testing in your different environments.)

**Comment by johannrichard** [comment]
Closed with 038e49fd09ec1a9010112d7077dc9ed55a97267b :octocat: :smile: 

I've had it tested with my complete setup (myStrom Lights, dingz Blinds, Buttons et al.) for over a day (+ some changes) and I'm quite confident it's much less buggy than `v1.7.1` (and definitely less buggy than `v1.8.0`). Thansk again you all for your contributions and feedback so far.

**Comment by granturism0** [comment]
Hello @johannrichard 
Thank you for your work and this effort.
I have tested this on myself. Looks just great so far :-)
Best regards

**Comment by johannrichard** [comment]
I've just released a `v2.0.1` hotfix on the main release train to solve a UI glitch with -- guess what -- the blinds. 😆🤣:octocat:

**Comment by granturism0** [comment]
👍🏻😂 Great!  Was just a point, which I still want to test😅

**Comment by granturism0** [comment]
I have one more improvement: can't we give the LEDs a clean name? For example, the LED+ device name, which we will read out.

**Comment by johannrichard** [comment]
> I have one more improvement: can't we give the LEDs a proper label? For example, the LED+ device name, which we will read out.

There's definitely room for many small improvements. Now that some of the bigger glitches are fixed, that should become easier, too.

**Comment by granturism0** [comment]
I have just discovered an issue in my setup. I have the DIP=1 setup. I have configured the motor but not the dimmers.
However, in my setup a dimmer now appears in the user interface. This is the dimmer of output 1.

**Comment by qx54** [comment]
How does the ALIVE check for the MyStrom buttons work?

It's my understanding the buttons reside in shutdown mode and only when the button gets pressed the OS boots. Is that wrong?

I can't ping the buttons nor access the API, so to me it looks like they're down (like they're supposed), thus wondering about the ALIVE entries in the log.

**Comment by johannrichard** [comment]
> How does the ALIVE check for the MyStrom buttons work?

They're undead. ☺️ Right now, the call to `getDeviceStateUpdate()` always resolves the promise and thus they're `ALIVE`. I have plans to change that to `UNKNOWN` at some point as we just don't know their state, but it was not highest priority anyway (since it's merely a `heartbeat` and status indicator in the logs).

Good observation though. ☺️😊
