### ISSUE TITLE
[BUG] Tilt angle has a correlation to the blind position

### ISSUE THREAD

**Issue by granturism0** [johannrichard/homebridge-dingz#149]
Hello @johannrichard 
I have just discovered another bug (in version 2.0.1) in relation to the tilt angle.
For example, if I have the blinds at 50% and set the tilt angle of the blinds to 0 degrees (TargetHorizontalTiltAngle = 0), then the blinds will go up completely (also to position 0).
So the angles of the slats somehow also control the blinds in terms of height.

**Comment by granturism0** [comment]
Line 990 must be blind: this.dingzStates.WindowCovers[id].position, and NOT 
blind: this.dingzStates.WindowCovers[id].lamella,

**Comment by johannrichard** [comment]
Fixed with #150. Thanks, @granturism0 for the contribution.
