### ISSUE TITLE
[FIX] Typo in log

### ISSUE THREAD

**Issue by simonnelli** [johannrichard/homebridge-dingz#155]
Change DingzDa to Dingz

[11/30/2020, 9:32:05 PM] [dingz] [dingz Küche] Identify! -> Who am I? I am a **DingzDaAccessory** listeting to the name of dingz Küche a.k.a. dingz Küche -> MAC: 246F28161968

**Comment by johannrichard** [comment]
Good catch. That one won't fix easily though as it is the class associated with the info saved in the cache and needed to restore your accessories on startup ... a sin from the early day of my code ... 🙈 🙉 🙊 

I'll keep it open and will see what I can do eventually.

**Comment by simonnelli** [comment]
Noticed because I've had to delete all cached accessories (strangely a auto discovered Dingz showed up, even though I've had auto discovery off all the time. After clearing the cache it din't show up again and I wasn't able to reproduce)
