### ISSUE TITLE
[BUG] Blinds not working in 3.1.2

### ISSUE THREAD

**Issue by granturism0** [johannrichard/homebridge-dingz#202]
Hello @johannrichard 
unfortunately the blinds do not work after version 3.0. With version 3.0 everything works great and in 3.1.2 they no longer work.
When I press the button for the blinds on the Apple Home nothing happens anymore. The switches still work though....
I have also removed everything and reinitialized, but without success.
Can you please take a look at this and I will thus go back to version 3.0.
Best regards
@granturism0

**Comment by granturism0** [comment]
OK, will test this :-)
Thought that the beta versions or the 3.1.2 are newer.

**Comment by johannrichard** [comment]
My `semantic-release` setup (or rather my dealings with it) are not yet perfect. The `alpha` versions will eventually always have a higher version number than the `latest` version. Just not yet. 🤣😂

**Comment by granturism0** [comment]
Easy!
The alpha version is working perfectly
