### ISSUE TITLE
[BUG]In Firmware 1.3.30

### ISSUE THREAD

**Issue by granturism0** [johannrichard/homebridge-dingz#418]
Hi @johannrichard 
From my point of view there is a bug in the newest firmware (maybe even before):
The current position of the blinds is no longer mapped properly, because the command for State no longer returns the current position (if I change the position via buttons), but the target value.
Could you possibly query the actual values with Shades and thus make a hotfix or workaround?
Greetings,
Granturismo

**Comment by johannrichard** [comment]
As this is a bug in the firmware [which should be fixed soon](https://forum.dingz.ch/d/73-fehler-in-firmware-1330), I would prefer not to implement a workaround here: this only clutters the code and makes it harder to maintain. Hope that's acceptable.

**Comment by johannrichard** [comment]
This was fixed in release 3.2.0 of the plug-in.
