### ISSUE TITLE
[BUG] Error with max. value for Tilt Angle

### ISSUE THREAD

**Issue by granturism0** [johannrichard/homebridge-dingz#419]
Hi @johannrichard 
In my logs i see a lot of this errors: [homebridge-dingz] This plugin generated a warning from the characteristic 'Current Horizontal Tilt Angle': characteristic was supplied illegal value: number 100 exceeded maximum of 90. See https://git.io/JtMGR for more info.
I think something is wrong with the maximum value.
PS: I use the latest firmware (1.3.30)
Greetings,
Granturismo

**Comment by johannrichard** [comment]
I know it's been a while since you reported the bug. In case you still use the plugin, I'd be grateful if you could check whether the beta indeed solves the issues here.

**Comment by johannrichard** [comment]
> I know it's been a while since you reported the bug. In case you still use the plugin, I'd be grateful if you could check whether the beta indeed solves the issues here.

N.B.: I tried to test it as much as possible. What's irritating me: if I move the slider in the Dingz WebUI to 100%, HomeKit will indeed display the maximum tilt angle of 90°. However, the slider just above that will display a value less than the maximum. OTOH, if I move the HomeKit Slides to 100% while the value of the angle is less than 90°, everything moves as well, but if I move the slider to the max, it somehow stalls. 

 
![IMG_376E520CFCA2-1](https://user-images.githubusercontent.com/189003/197578321-eb83d39b-a727-4f0c-a566-3ec0397b468b.jpeg)

**Comment by johannrichard** [comment]
Did some more tests (and tweaks to the code). The warnings are (mostly IMHO) gone now and the values set should now be all converted between ° and % (and vice-versa) at the right place.
