### ISSUE TITLE
[HELP] myStrom Button

### ISSUE THREAD

**Issue by sadanro100** [johannrichard/homebridge-dingz#465]
I've managed to get the button to send a heartbeat to the plugin as follows:

`[4/20/2022, 3:17:10 PM] [myStrom] [HEARTBEAT] ::ffff:IP_ADDRESS`

I haven't been able to figure out how to bind this to an action in Homebridge.

My goal is to get the the button to toggle other Homebdridge switches, preferably distinguishing the button event triggered (press / double press / long press) to choose which device.

Is that possible? 

If not, how can I use this device at all?

**Comment by sadanro100** [comment]
For some reason the button wasn't showing up in Home app, now it did it's pretty self explanatory.

**Comment by sadanro100** [comment]
Even after setting up the actions in the home app, when I press the button I get the heartbeat in Homebridge's log, but the actions are not performed.

![image](https://user-images.githubusercontent.com/14843839/165460889-7ce8a5f2-07ba-4e18-9a46-90c8afb9dc0e.png)

**Comment by johannrichard** [comment]
Sorry for being slow to respond and sorry to hear about your issues with the plugin and the buttons. The heartbeat alone does not mean the button press is recorded. 

Usually when you press a button, the respective action should quickly be highlighted with a darker background in the HomeKit App. If you enable debugging, you should also see an Action in the log (single, double, long press):

```
Button (MAC) pressed -> (ACTION)`
```

The WiFi Buttons are a bit finicky though as they only rarely connect to WiFi.

**Comment by johannrichard** [comment]
What you can do to check if the button is correctly configured:

In the settings in the MyStrom App, check under settings whether the Trugger URL is correctly set to your Homebridge servers' IP address. 

![image](https://user-images.githubusercontent.com/189003/197472134-32cf15d5-8743-45b8-b9d4-ce6208f240e7.png)

![image](https://user-images.githubusercontent.com/189003/197472170-ccbfe6d2-891c-4e3b-9c85-e26fa213c768.png)

If not, you can correct it in the MyStrom App directly.

**Comment by sadanro100** [comment]
I gave up on this plugin back then. What I ended up using was Homebridge Webhooks and setting the button actions as such:

curl --location -g --request POST 'http://BUTTON-IP/api/v1/action/single' \
--data-raw 'get://raspIP:51828?accessoryId=ID&state=true'

The downside of it is that I had to configure port forwarding and since the call goes out to china, there's algo a little delay.

Is your plugin supposed to work locally?

**Comment by johannrichard** [comment]
Yes the plug-in works locally – there's no cloud involved.

**Comment by sadanro100** [comment]
Does this plugin work with this version of the button?

![image](https://user-images.githubusercontent.com/14843839/212187563-05725fc7-f4a0-4dda-b4f5-551230b54aa9.png)

**Comment by johannrichard** [comment]
Yes, these should in principle (and practice :-)) work; see the Wiki page on [restrictions](https://github.com/johannrichard/homebridge-dingz/wiki/myStrom-buttons) for some important details.

**Comment by sadanro100** [comment]
Hi there, I'm trying the plugin once again. I had it discover my button successfully but the URL was not set. I set it myself as follows.

![image](https://user-images.githubusercontent.com/14843839/217132604-ae7cb395-f9b9-4307-b210-641e9c274585.png)

However nothing shows up in the logs (except the call made to my webhook server mentioned here https://github.com/johannrichard/homebridge-dingz/issues/465#issuecomment-1288612246) and the action chosen for single press in the button screen in Home app never gets triggered.

When I use my external address instead of my homebridge internal address as the button URL (and setup port forwarding) I do get a heartbeat as follows, but that's about it...

`[06/02/2023, 23:23:57] [myStrom] [HEARTBEAT] ::ffff:5.148.178.23`
