### ISSUE TITLE
[FEATURE] Add support for MyStrom Button+ 2

### ISSUE THREAD

**Issue by petter1** [johannrichard/homebridge-dingz#540]
I recently bought the MyStrom button+ 2 unknowing, that it has no direct HomeKit support. Now I found this repo and recognised, that it is not in this plugin yet. 

The button+ 2 is a device with 4 inputs and it can differentiate between press, double press and long press on each.

https://mystrom.ch/de/wifi-button-plus/
https://mystrom.ch/de/support/wifi-button-plus-2/

**Comment by johannrichard** [comment]
I'm already working on it ... expect an alpha/beta release soon (no ETA though)

**Comment by petter1** [comment]
Awesome 😍 nice to hear!
I would love to help in development if anyhow possible 😁

Btw, I live in Switzerland as well

**Comment by petter1** [comment]
I started to Analyse the code in order to see what has to be changed
I saw, that the dingz already has a four button layout like dingz

So we could go the same way with the variable module
 With 1,2,3,4 btn1,btn2,btn3,btn4

API to set WebHook for it is same as with the one button, just with definition which button after action: to POST
v1/action/${module}/<generic|single|double|long>

I could not find, where you define the WebHook action or listen for it yet.
I want to test, if the plugin works, if I hack in the webHook string manually using cURL

**Comment by johannrichard** [comment]
> So we could go the same way with the variable module With 1,2,3,4 btn1,btn2,btn3,btn4

Yes that’s right. I’m close to release an alpha version, just waiting for a button to arrive on my doorstep to do some real-world testing before releasing it. If you give me a day or two I might be able to do so soon. ☺️

The webhook is handled by the platform code `platform.ts`.

**Comment by petter1** [comment]
😂🫣you are too fast
I wanted to learn TS with this project 

Maybe I can enhance device discovery or do a web view 😃 I guess that would be a nice addition.

If you want, i could do real world testing tonight 
😁

**Comment by johannrichard** [comment]
Here we go: [v3.3.0-alpha.1](https://github.com/johannrichard/homebridge-dingz/releases/tag/v3.3.0-alpha.1) should be available. Beware: It's really alpha, I have not yet tested it with a real Button+ and things will break! 

PS: Of course, contributions are welcome. This has mostly been a "one trick pony" (a.k.a. me) story so far. It might thus take some time for me to get used to real collaborative development and to get some process & workflows agreed on that would make the best use of our collective effort.

**Comment by johannrichard** [comment]
Furthermore, I will not be very responsive the new few days. If you run into big problems, you might of course roll-back to the latest stable version.

**Comment by petter1** [comment]
I could not connect with auto discovery: Unknown device 118
Log is created in platform.ts Row 1002
I could not find a 
```
case DeviceTypes.MYSTROM_BUTTON_PLUS_2G
```
But all the other buttons, so I guess it needs to be there as well

If I try it manually I get nothing in the logs until timeout

Will research further tomorrow 😃

**Comment by johannrichard** [comment]
The perils of early commits. 🫣🤣 Missed that one with all the on-off coding over the last days. 

This should be an easy one, if you are keen on contributing you could try a PR for that one too, besides #544 (if you do so, keep the two PRs separate).

**Comment by petter1** [comment]
I think I had understood what the problem is and added the code accordingly, but I did not find out how I can test the plugin. I was not able to install my fork into my homebridge, since it is not published on npm.. 
The way hombridge has described to test `npm link` does not work, and I could not figure out how to do it with yarn..

**Comment by johannrichard** [comment]
> The way hombridge has described to test in vevelopment: npm link did not work, and I could not figure out how to do it with yarn... yet

Since the modules are managed with `yarn`, you must have all the relevant commands be preceded by `yarn`. There's a run script called `debug` in `package.json` that will do all the necessary for you (except for linking with `npm link`):

```shell
$ yarn run debug
```

That should compile the plug-in, and then `homebridge` so that it's aware of the plug-in.

**Comment by johannrichard** [comment]
There's update documentation on [how to add and configure the Button+](https://github.com/johannrichard/homebridge-dingz/wiki/myStrom-buttons) in the Wiki.
