### ISSUE TITLE
[FEATURE] show MAC address of registered devices in log

### ISSUE THREAD

**Issue by petter1** [johannrichard/homebridge-dingz#544]
print the MAC address in the log every time a device is mentioned 

I use switches directly with HomeKit and ignore them in the hombridge plugin. I have no way to find out the MAC address (other then checking in MyStrom app, via DHCP server or reading from device sticker)

**Comment by johannrichard** [comment]
Some users didn't like the standard logging of all the discovered MAC's. They're printed, but only in debug mode and only if auto-discovery is disabled. If you turn on debug mode in Homebridge you'll see them. 

In case you want to suggest improvements to that: have a look into `src/platform.ts`: what you look for is around lines 890-1000. 

Maybe a nice little challenge for a first PR?
