### ISSUE TITLE
[BUG] dingz Lamella Wrong Angle value

### ISSUE THREAD

**Issue by whos-c** [johannrichard/homebridge-dingz#555]
homebridge-dingz crashes while moving the lamella blind due to miscalculated angle. If the lamella is set to 100% and 90°, Homebridge value is 100% and 111°. Identified the following two lines which lead to this error, could you take a look? Thanks!

Log:
```
[dingz] Blinds moving:  down --> 0
[dingz] Setting WindowCovering 1 to position 0 and angle 111°
[dingz] POST http://192.168.178.98/api/v1/shade/1
[dingz] Error: Request failed with status code 400 (POST http://192.168.178.98/api/v1/shade/1)
[dingz] HTTP undefined Request failed with status code 400 Bad Request--> 192.168.178.98
```
https://github.com/johannrichard/homebridge-dingz/blob/a9e848b3727d00fdcceab0056d325c4080af0d2e/src/dingzAccessory.ts#L949
https://github.com/johannrichard/homebridge-dingz/blob/a9e848b3727d00fdcceab0056d325c4080af0d2e/src/dingzAccessory.ts#L992

**Comment by johannrichard** [comment]
🙈 Could you please provide additional information The `dingz` firmware versions are notorious for very varying "interpretations" of the lamella angle and how they report it, and I try (...) to somehow deal with this.

See for example the following lines just a bit further down.

https://github.com/johannrichard/homebridge-dingz/blob/a9e848b3727d00fdcceab0056d325c4080af0d2e/src/dingzAccessory.ts#L1020-L1022

To look into it, I would need at least the version of your dingz' firmware and some additional status dumps. You can get the FW version and the lamella config & status by opening the following in your browser and posting the output here (obfuscate the MAC address from the info endpoint as this is potentially sensitive)

```
http://<IP>/info
http://<IP>/api/v1/blind_config
http://<IP>/api/v1/state
```
See #419, #371 for the never-ending story (different FW versions with very different behaviours).

**Comment by johannrichard** [comment]
Note to self: irrespective of the cause for the wrong values, some more sanity checks and edge-case provisions would be helpful here.

**Comment by pisarenko-net** [comment]
Can confirm that I'm seeing the same issue.

 - `/info/`
```
{"version":"1.3.30",...}
```
 - `/api/v1/blind_config`
```
{"blinds":[{"auto_calibration":true,"state":"Initialised","invert_direction":false,"lamella_time":1.8,"shade_up_time":34.12,"shade_down_time":33.78,"type":"lamella_90","min_value":0,"max_value":100,"name":"Motor"},{"auto_calibration":true,"state":"Initialised","invert_direction":false,"lamella_time":1.8,"shade_up_time":0,"shade_down_time":0,"type":"lamella_90","min_value":0,"max_value":100,"name":"Motor"}]}
```
 - `/api/v1/state`
```
{"dimmers":[],"blinds":[{"moving":"stop","position":100,"lamella":100,"readonly":false,"index":{"relative":0,"absolute":0}},{"moving":"stop","position":100,"lamella":0,"readonly":false,"index":{"relative":1,"absolute":1}}],"led":{"on":false,"hsv":"0;0;100","rgb":"FFFFFF","mode":"hsv","ramp":1023},"sensors":{"brightness":49,"light_state":"night","room_temperature":23,"uncompensated_temperature":40.875,"temp_offset":0,"cpu_temperature":56.11,"puck_temperature":37,"fet_temperature":37.2,"input_state":null,"person_present":0,"power_outputs":[{"value":0},{"value":0},{"value":0},{"value":0}]},"thermostat":{"active":false,"out":0,"on":false,"enabled":true,"target_temp":21,"mode":"heating","temp":23,"min_target_temp":17,"max_target_temp":31},"wifi":{"version":"1.3.30",...},"time":"2023-01-28 15:23:23","config":{"timestamp":1674914600}}
```

**Comment by pisarenko-net** [comment]
Interestingly, the control works from Homekit itself. It's just from the Homebridge UI itself that the functionality doesn't work correctly.

**Comment by johannrichard** [comment]
> Interestingly, the control works from Homekit itself. It's just from the Homebridge UI itself that the functionality doesn't work correctly.

Just to be sure I understand correctly: if you use the Homebridge UI to control the blinds, then (and only then) Homebridge crashes?

**Comment by pisarenko-net** [comment]
> > Interestingly, the control works from Homekit itself. It's just from the Homebridge UI itself that the functionality doesn't work correctly.
> 
> Just to be sure I understand correctly: if you use the Homebridge UI to control the blinds, then (and only then) Homebridge crashes?

Yes. To be more precise Homebridge UI doesn’t crash: it logs a failed request with a 400 response code. It just fails to control blinds but keeps operating.

**Comment by johannrichard** [comment]
Thanks @pisarenko-net and @whos-c for the reporting and patience. The additional info helped me (finally) identify the culprit. An alpha-version with a fix should be out soon, followed by a beta a few days later. As I don't have all the different FW versions to test with, I will depend on you providing some input on the fix. You can wait for the beta if you wish.
