### ISSUE TITLE
[BUG] Plugin funktioniert nicht auf Hoobs

### ISSUE THREAD

**Issue by claude1984** [johannrichard/homebridge-dingz#56]
Hallo
Ich versuche seit einiger Zeit die Dingz-Schalter in mein Hoobs zu integrieren, was einfach nicht klappt. Egal ob per auto-discovery oder per manueller Eingabe.

Habe das Plugin schon mehrmals entfernt und wieder installiert. Keine Änderung. Auch die MyStrom-Geräte werden nicht erkannt. (Nur vom MyStrom-Plugin, durch manuelle Eingabe, welches glaube ich auch von Dir kommt)

Mache ich was falsch?

Front:
Firmware 1.1.49
Webinterface 2.3.13
Hardware 1.1.2
Model DZ1F-4B

Base:
Bootloader 1.0.0
Firmware 1.1.18
Hardware 1.1.2
Model DZ1B-4CH

 - Homebridge Server: Raspberry PI3b mit Hoobs
 - Plugin Version 1.6.0
 - Node.js Version 12.16.3
 - Homebridge Version Hoobs 3.2.6

Ich betreibe keinen proxy und habe nichts besonderes im Netzwerk. 
Auch keinen REST-API-Token vergeben. Es sollte eigentlich alles „standard“ sein.

**Comment by johannrichard** [comment]
Hallo,

Danke für den Bug Report (und die Geduld). 

Was helfen würde: ein Auszug der Log Datei von Hoobs wenn es startet, mit dem "Debug" Modus ein. (Siehe https://support.hoobs.org/docs/5ea6858d0ab68b0344e872e3)

Interessieren tun alle Meldungen des "dingZ" Plugins (falls es überhaupt welche hat und das Plugin tatsächlich startet).

Du kannst as Log hier posten, achte darauf dass Du allfällige Infos wie die HomeKit PIN, IP Adressen etc. anonymisierst bevor Du die Logs hier einfügst. Falls du die Möglichkeit hast, ein Test-Hoobs auf einem anderen System einzurichten und dort nur das dingZ Plugin einbindest, wird das debugged allenfalls einfacher (vorausgesetzt dort funktioniert es auch nicht).

PS: Hoobs ist (leider) in einigen Bereichen anders geschaltet als ein "normales" Homebridge. Das kann ein Grund für Probleme sein den ich nicht zwingend lösen kann.

**Comment by claude1984** [comment]
Hallo,
Ich habe Hoobs im Debug-Modus gestartet. Hier zwei Screenshots. Danach erschein niewieder ein Hinweis auf [Dingz].
![CEE48A3E-E4D0-44B7-B53D-9DA3F3839ADB](https://user-images.githubusercontent.com/70483392/91838402-b7e38680-ec4d-11ea-9b2f-547513cae0bf.jpeg)
![FD3E7111-B47B-4FC9-9605-AEB472E77760](https://user-images.githubusercontent.com/70483392/91838406-bb770d80-ec4d-11ea-8d34-f68664f5d71f.jpeg)

**Comment by johannrichard** [comment]
Danke für die Screenshots. Was mir auffällt: die Plugins welche funktionieren werden alle als "homebridge-xyz.abc" geladen und registriert. Das DingZ plugin dagegen lädt als Platfom "DingZ". Ich werde dem nachgehen müssen, melde mich wenn ich mehr weiss.

**Comment by johannrichard** [comment]
Nach etwas austesten (musste eine HOOBS installation hochziehen) ist es wohl im Moment so, dass Hoobs etwas vom Plugin erwartet, welches es nicht anbietet, weshalb HOOBS das Plugin nicht komplett laden kann. Entweder ein Fehler im Plugin oder eine Abhängigkeit im Code. Ich habe Dir leider keine kurzfristige Lösung aber versuche hier im Rahmen des Möglichen bald den Fehler zu isolieren.

**Comment by johannrichard** [comment]
There are [two ways](https://github.com/homebridge/homebridge/blob/117927f3cb2916c16c21735586a7ec62c1218d72/src/api.ts#L183-L184
) to register a platform in the Homebridge API:

https://github.com/homebridge/homebridge/blob/117927f3cb2916c16c21735586a7ec62c1218d72/src/api.ts#L183-L184

Both are valid, but apparently, @hoobs-org depends on plugins to use the full call which includes the plugin name (`homebridge-dingz`) in addition to the Platform name.  There are a number of plugins running into the same issue and while it can be fixed, it would indeed be important that @hoobs-org update their code to account for homebridge plugins which use the shorthand version.

**Comment by johannrichard** [comment]
@claude1984: Ich werde ASAP einen BUGFIX implementieren und dann das Ticket schliessen. Damit weisst Du dann, wenn Du ein Update machen kannst.

**Comment by johannrichard** [comment]
Fixed in v[1.6.1] 

[1.6.1]: https://github.com/johannrichard/homebridge-dingz/compare/v1.6.0..v1.6.1

**Comment by johannrichard** [comment]
@claude1984 es kann etwas dauern bis die neue Version v1.6.1 in Hoobs sichtbar wird.

**Comment by claude1984** [comment]
Super, vielen Dank. Bin schon gespannt!

**Comment by claude1984** [comment]
Funktioniert! 
Top!!!!
Vielen Dank!!!
