### ISSUE TITLE
v.1.2.1 not shown

### ISSUE THREAD

**Issue by simonnelli** [johannrichard/homebridge-dingz#6]
When installing your plugin v.1.2.1 isn't pulled. Latest version is shown as 1.2.0

**Comment by johannrichard** [comment]
It was not yet released on NPM. Is out now.

**Comment by johannrichard** [comment]
PS: I'm still trying to get the CHANGELOG into Homebridge. Hope to have it at some point. Please note the breaking changes of v1.2.1!

**Comment by simonnelli** [comment]
Thank you! I do see the changelogs AFTER installing in CONFIG UI X
