### ISSUE TITLE
Photovoltaic values

### ISSUE THREAD

**Issue by Pythonaire** [johannrichard/homebridge-dingz#610]
**Describe the feature requested**
i thought, the myStrom Wifi Switch is fully Homekit compatible (MFI) and able to read power Consumption and proceed these data to the Homekit API (like Eve Energy ""E863F10C-079E-48FF-8F27-9C2605A29F52"), but it seems to me, it isn't. It is a simple Outlet and temperature accessory in the homekit environment (free to use services and characteristics, not MFI. if im right, the Homekit certified label is a fake). To read the solar data, a separate App is needed. I want to read the consumption data and push them to the homekit API.

**Examples and context**
see EVE Energy integration into Homekit. Maybe, by creating an account on the myStrom cloud base, i get a token to access the Wifi Switch? Maybe, i can use this token to read the solar data by myself and transport them to the Homekit as power consumption values?

**Additional context**
I made my own Homekit Connector for my solar device in the eve energy style (https://github.com/Pythonaire/Photovoltaic)  and hoped it could be easier with mystrom.

**Comment by johannrichard** [comment]
Hi,

I'm uncertain if I correctly understand what you tried. In any case, there are two ways to use (newer) myStrom Switches with HomeKit:

- with homebridge via this (unofficial!) homebridge plugin: HomeKit is not certified, as with all homebridge plugins, 
- with native HomeKit integration (for some switches provided via Firmware upgrade) by https://mystrom.ch - the manufacturer of the switches (See https://mystrom.ch/support/apple-homekit/)

If you discuss the latter, I'm afraid this is the wrong place to create a ticket. You should address your concerns to myStrom directly: https://mystrom.ch/support/.  I suspect it is this, hence I close the ticket.

If your concern is EVE compatibility of this plugin: this has not been implemented (yet) - but could be if there are requests for it. If that is the case, please feel free to reopen the ticket.

If your concern is something else, then I'm afraid I didn't understand exactly what you mean and I would kindly ask you to elaborate.

**Comment by Pythonaire** [comment]
Sorry, if i'm not correct in describing the idea.
But i see, there is not a chance to provide energy values from the mystrom wifi switch to the Apple Homekit.
