### ISSUE TITLE
[FEATURE] Add support for myStrom motion sensor

### ISSUE THREAD

**Issue by qx54** [johannrichard/homebridge-dingz#87]
Ordered a myStrom motion sensor because I thought motion sensors are supported. Only now realized, this didn't apply to the myStrom devices, only to the Dingz devices.

Any plans for adding myStrom motion sensor support to the plugin?

Thanks

**Comment by johannrichard** [comment]
So far I had not planned to implement it, mostly because I don't own a WiFi Motion Sensor. However, the API of the Motion Sensor is similar to the dingz'. So if you're willing to test "untested" code (ideally in a separate environment), then it's realistic to get support relatively quick.

**Comment by qx54** [comment]
Totally willing to test untested code. Also willing to sponsor a device, although I think MyStrom should do that. Please let me know.

**Comment by johannrichard** [comment]
:smile: myStrom has already been quite generous (but the motion sensor was not part of the sponsored devices). I'll do w/o one, for the time being, you willing to test should be sufficient. 😃

**Comment by qx54** [comment]
Great, it's much appreciated! Can't wait :)

PS: The myStrom button is working great with this plugin.

**Comment by johannrichard** [comment]
😅 I might need some help though to identify a few info items of a WiFi Motion Sensor. Could you access the following URLs of your device and post what exactly you get (but change/obfuscate things like the MAC address and IP addresses or the SSID of your WiFi for privacy reasons):

`http://[Sensor IP]/api/v1/info`
`http://[Sensor IP]/api/v1/device`

Having this info will allow me to implement auto-detection of the motion sensors.

**Comment by qx54** [comment]
http://[Sensor IP]/api/v1/info:

```{"version":"3.82.46","mac":"FCF5C425BD60","type":110,"ssid":"MyWifi","ip":"","mask":"","gateway":"","dns":"","static":false,"connected":true}```

The ip, mask, gateway etc. were empty just like posted above.

http://[Sensor IP]/api/v1/device returns a 404 error.

**Comment by qx54** [comment]
`http://[Sensor IP]/help` resturns:

```
GET info
GET info.json[?timestamp=<STR 1..32>]
GET networks
GET networks.json[?timestamp=<STR 1..32>]
GET wps
GET wps.json[?timestamp=<STR 1..32>]
GET ip
GET hidden?network=<STR 1..32>
GET rest[?enable=<BOOL false|true>][&token=<STR 0..256>]
GET panel[?enable=<BOOL false|true>]
GET connect?network=<STR 1..32>[&password=<STR 0..64>][&ip=<IP>][&mask=<IP>][&gateway=<IP>][&dns=<IP>][&hidden=<UINT 0..1>][&static=<UINT 0..1>]
GET commit.phtml?network=<STR 1..32>[&password=<STR 0..64>][&ip=<IP>][&mask=<IP>][&gateway=<IP>][&dns=<IP>][&hidden=<UINT 0..1>][&static=<UINT 0..1>]
POST download?path=<STR 1..127>&sum=<STR 40..40>
GET 
GET temp
GET api/v1/temperature
GET api/v1/light
GET api/v1/motion
GET api/v1/sensors
GET api/v1/action
GET api/v1/action/pir/<ENUM generic|night|twilight|day|rise|fall>
POST api/v1/action/pir/<ENUM generic|night|twilight|day|rise|fall>
GET api/v1/scan[?ssid=<STR 1..32>]&callback=<STR 1..63>
GET api/v1/scan[?ssid=<STR 1..32>]
POST api/v1/connect ssid=<STR 1..32>&passwd=<STR 1..63>[&ip=<IP>][&mask=<IP>][&gw=<IP>][&dns=<IP>]
POST api/v1/wps
GET api/v1/info
GET api/v1/ip
GET api/v1/settings
POST api/v1/settings [rest=<BOOL false|true>][&panel=<BOOL false|true>][&referer=<BOOL false|true>][&token=<STR 0..256>][&hap_disable=<BOOL false|true>][&name=<STR 0..50>]
GET api/v1/settings/pir
POST api/v1/settings/pir [backoff_time=<UINT 1..84600>][&led_enable=<BOOL false|true>]
GET api/v1/settings/pir/thresholds
POST api/v1/settings/pir/thresholds night=<UINT 0..65535>&day=<UINT 0..65535>
GET api/v1/led
POST api/v1/led/<ENUM enable|disable>
GET help
```

**Comment by qx54** [comment]
api/v1/light:
```
{
	"success":	true,
	"intensity":	228,
	"day":	true,
	"raw":	{
		"adc0":	228,
		"adc1":	38
	}
}
```

api/v1/motion:
`{"success":true,"motion":true}`

api/v1/sensors:
```
{
	"motion":	true,
	"light":	227,
	"temperature":	21.350000381469727
}
```

Hope this helps. Let me know if you need anything else.

**Comment by qx54** [comment]
I played around with the API and noticed the day value of `api/v1/light` stays `true` even when the light intensity is below the treshold.

api/v1/settings/pir/thresholds:
´´´
{"night":30,"day":100}
´´´

api/v1/light:
```
{
	"success":	true,
	"intensity":	5,
	"day":	true,
	"raw":	{
		"adc0":	5,
		"adc1":	1
	}
}
```

Maybe it matters.

**Comment by johannrichard** [comment]
Thanks for the additional info. In polling mode, only the "raw" values (i.e. motion/no motion, ambient light level and temperature) matter. 

In case someone prefers the "push" mode (i.e. the sensor calls an action URL, not unlike the buttons, on movement), I will have to see how I implement this. One possibility would be to have one motion sensor per "type" of motion:

* day 
* night
* twilight
* rise / fall ("normal" motion)

However, I think this is something you can also model in HomeKit directly and thus having just one motion sensor reacting to any motion (rise/fall) would be sufficient in these cases. 

😁 In any case, the myStrom/DingZ APIs are far from perfect (as is the new accessory), but making progress already :wink: 

I'll let you know once I have a test package ready to be installed. For today, I call it a day (night). 

![IMG_5AE8F8C2DF8E-1](https://user-images.githubusercontent.com/189003/98735111-2e65d880-23a3-11eb-81eb-f74ddea4c990.jpeg)

![Motion Sensor](https://user-images.githubusercontent.com/189003/98735210-4d646a80-23a3-11eb-9ec1-aea0298b1e31.jpg)

**Comment by qx54** [comment]
I was actually planning to use the push mode since the pull mode adds unnecessary network activity and will delay the trigger by up to 2.5 seconds if I understand that correctly. 

Push mode will still work with the new implementation, just not include the day/night/twilight information, correct? I can definitely build this logic within Homekit, thus that's not a big issue.

**Comment by johannrichard** [comment]
> I was actually planning to use the push mode since the pull mode adds unnecessary network activity and will delay the trigger by up to 2.5 seconds if I understand that correctly.

Yes, it polls the sensor every 2000 ms. In terms of delay, it might indeed be that you have less delays with the push mode, although in my experience, the action calls also take a bit of time with the buttons and even with the dingz that's usually constantly connected. Right now, I'm working on the poll (it's easier 😁) but push will definitely also come.

> Push mode will still work with the new implementation, just not include the day/night/twilight information, correct? I can definitely build this logic within Homekit, thus that's not a big issue.

Exactly. It will send a "trigger" event whenever motion / no motion is detected. 
> 
> Good night 😴

**Comment by johannrichard** [comment]
Testing time ... 😊 

Caveats: 
* definitely alpha (nightly ...) code for testing, so use a test environment whenever possible -- things will break 😬   
* if all went well, auto-detection should work form the id provided
* if the accessory is not detected, try adding it manually 
* in case of trouble / errors, debug output will help (from `homebridge -D` / setting the debug switch in `hombridge-config-ui-x`)
* only *poll* is implemented right now (see above, *if* the sensor accessory is working in poll mode, adding push should be *fairly* easy, using what I've built for the dingz) 

* install with `npm i -g homebridge-dingz@nightly`  (or if you use docker, `docker exec homebridge npm install homebridge-dingz@nightly` (assuming that your docker container is named `homebridge`. If it has a different name I trust you will know what to do. 😁)

**Comment by qx54** [comment]
✔️ Successfully installed.
✔️ Motion sensor was already manually configured previously.
✔️ I can see the temperature, light and motion accessories.
✔️ Motion got triggered and Homekit automation rule got executed.

Awesome, many thanks!

Question: When/how does the motion sensor go from triggered to untriggered state?

**Comment by johannrichard** [comment]
Great to hear it works already. :smile: 

Regarding the "no motion trigger": this can be configured. 

According to the [API](https://api.mystrom.ch/#846a0c80-d156-4d3b-bdf5-f38b06231d18), this is defined by the `backoff_time` setting at the `http://{{pir_ip}}/api/v1/settings/pir` endpoint. The default "back off" time is 10 seconds.  

> [backoff time] defines the minimum frequency between successive motion detections. If motion is detected during this period, this time is extended by the defined value without another motion event notification. Units are seconds.

**Comment by qx54** [comment]
I played around with automation rules and love it. Thank you very much @johannrichard !

Can you add a setting for the polling interval? As long as there's no push option I prefer to use a shorter interval for faster response time. While the many requests are not ideal, my Wifi should be able handle that 😁 

In case anybody stumbles upon this Github issue in the future, here's some information that might help:

1. You need the Eve app to create rules with brightness as a condition because it's not possible with the native Apple Home app.

2. To change the back off time (default on my device was 180) you can use the following command:
`curl -i -X POST -H 'Content-Type: application/json' -d '{"backoff_time":10}' http://{{pir_ip}}/api/v1/settings/pir`

**Comment by johannrichard** [comment]
Later today, you might want to update to the latest `nightly` version (`1.6.2-nightly.1`) - and change the plugin settings from polling to push for the motion sensors. 😉

Please report any issues back here. If there are none, I will then publish an official version in the coming days and close this ticket. 

PS: the suggestion to make polling an option that can be configured also makes sense, might implement it for all (motion) polling, but this will need some additional time. I understand that push is in any case your preferred mode.

**Comment by qx54** [comment]
That is awesome! 🙇 The push method works perfectly.

Questions for a better understanding:

1. I assume the light value also gets sent with a push so the conditions of the automation rules will work with the (current) light value of the moment the motion got triggered?

2. Does the light (and temperature) value get updated in the accessory after the back off time elapsed? I kinda have this impression but might be wrong.

> the suggestion to make polling an option that can be configured also makes sense, might implement it for all (motion) polling, but this will need some additional time.

I don't mean to be pushy (no pun intended) and don't need that setting anyway with the push method working, but I'm curious what you mean by that? To me it seems like reading the polling interval value from the settings is peanuts compared to what you did to make the myStrom Motion Sensor work without even being able to test it on your own? 😄

**Comment by johannrichard** [comment]
> That is awesome! 🙇 The push method works perfectly.

😊 glad to hear that. 

> 1. I assume the light value also gets sent with a push so the conditions of the automation rules will work with the (current) light value of the moment the motion got triggered?

Good point (and reflection): even with push, we still have to poll the device regularly to update the temperature (which is not sent with the motion trigger ... ). So right now, the plugin will continue to poll. There's still some room to optimize the code there and will eventually follow.

> 2. Does the light (and temperature) value get updated in the accessory after the back off time elapsed? I kinda have this impression but might be wrong.

See above. It's likely the polling updating the values -- whether the motion sensor internally updates them or not during the backoff time I cannot tell (you can observe this yourself, just reload the `/api/v1/sensors` before, during and after the motion trigger happened and compare these to the values you see in Homebridge/HomeKit. This I can only simulate, but not test.)

> > the suggestion to make polling an option that can be configured also makes sense, might implement it for all (motion) polling, but this will need some additional time.

> I don't mean to be pushy (no pun intended) and don't need that setting anyway with the push method working, but I'm curious what you mean by that? To me it seems like reading the polling interval value from the settings is peanuts compared to what you did to make the myStrom Motion Sensor work without even being able to test it on your own? 😄

:grin: Fair point. Easy is sometimes hard. Or vice-versa. I already had all the bits and pieces for the poll and push (dispersed between WiFI Switch, Button and the Dingz) and "just" had to pull it together, get some real data (thanks for that, again) and have someone to test. 

The configurable polling interval, however, is something new and so the risk for errors is bigger. Plus, I have to settle with myself if there should be a minimum poll interval (and a maximum), or how I deal with the various timeouts I've included in the poller code (i.e. what happens if the time I wait for a response is suddenly much longer than the polling interval if there's a network problem? Do I have to adjust these timeouts dynamically, etc.) and more.

**Comment by qx54** [comment]
> even with push, we still have to poll the device regularly to update the temperature (which is not sent with the motion trigger ... ). So right now, the plugin will continue to poll.
In this case my question didn't really matter since the light should be up to date anyway. I assume the same 2000 ms interval?

> The configurable polling interval, however, is something new and so the risk for errors is bigger. Plus, I have to settle with myself if there should be a minimum poll interval (and a maximum), or how I deal with the various timeouts I've included in the poller code (i.e. what happens if the time I wait for a response is suddenly much longer than the polling interval if there's a network problem? Do I have to adjust these timeouts dynamically, etc.) and more.
I see, it's mainly about dependencies. It would be nice to be able to change the polling interval to 2 or 5 minutes when using the push mode, but it's not really important.

Thanks again for the great implementation, it's much appreciated 😄
